---
--- Generated by Luanalysis
--- Created by walker.dou.
--- DateTime: 2023/5/22 13:23
---


--function fwrite(fmt, ...)  ---> 固定的参数fmt
--return io.write(string.format(fmt, ...))
--end
--
--fwrite("runoob\n")       --->fmt = "runoob", 没有变长参数。
--fwrite("%d%d\n", 1, 2)   --->fmt = "%d%d", 变长参数为 1 和 2

-- 输出结果为：

-- runoob
-- 12
--
--function a(...)
--   local  a,b,c,d,e = select(2, ...)
--    print(select(2, ...))
--    print(a,b,c)
--end
--a(2,4,6,8,10)
--


--function foo(...)
--    for i = 1, select('#', ...) do
--        -->获取参数总数
--        local arg = select(i, ...); -->读取参数
--        print("arg", arg);
--    end
--end
--
--foo(1, 2, 3, 4);

--输出结果为：
--arg    1
--arg    2
--arg    3
--arg    4

--array = {"lua", "Tutorial"}
--
--for i= 0, 2 do
--    print(array[i])
--end

--输出结果为 nil Lua Tutorial
fruits = {"banana","orange","apple", [1] = "1"}

---- 在末尾插入
--table.insert(fruits,"mango")
--print(table.concat(fruits))
--print(fruits.a)

for i, v in pairs(fruits) do
    print(i, v)
end
