server:
  port: 6666
spring:
  application:
    name: dp-demo
  datasource:
    url: jdbc:mysql://localhost:3307/demo?serverTimezone=UTC
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
debezium:
  datasource:
    flushInterval: 10000
    historyFile: E:/debezium/test/history/custom-file-db-history.dat
    hostname: localhost
    password: 123456
    port: 3307
    serverId: 1
    serverName: name-1
    storageFile: E:/debezium/test/offsets/offset.dat
    tableWhitelist: test.test
    user: root


