/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_jni_HeicConverter */

#ifndef _Included_org_example_jni_HeicConverter
#define _Included_org_example_jni_HeicConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_jni_HeicConverter
 * Method:    convertHeicToJpeg
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_example_jni_HeicConverter_convertHeicToJpeg
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
